name: Python CI with Pytest and Selenium

on:
  push:
    branches:
      - '*'  # Trigger on any push to any branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >-
          --shm-size=2g
        ports:
          - 4444:4444

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Build Backend Docker Image
    - name: Build Backend Docker Image
      run: |
        cd nextjs-fastapi/backend
        docker build -t nextjs-backend .

    # Build Frontend Docker Image
    - name: Build Frontend Docker Image
      run: |
        cd nextjs-fastapi/frontend
        docker build -t nextjs-frontend .

    # Create a custom Docker network
    - name: Create custom Docker network
      run: |
        docker network create my-network

    # Run Backend Docker Container
    - name: Run Backend Docker Container
      run: |
        docker run -d --name nextjs-backend --network my-network -p 8000:8000 nextjs-backend

    # Run Frontend Docker Container
    - name: Run Frontend Docker Container
      run: |
        docker run -d --name nextjs-frontend --network my-network -p 3000:3000 nextjs-frontend

    # Wait for services to start
    - name: Wait for services to start
      run: |
        sleep 10  # Adjust the sleep time if necessary

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sqlalchemy pytest fastapi selenium chromedriver_autoinstaller httpx

    # Run unit tests (non-Selenium)
    - name: Run unit tests
      run: |
        set PYTHONPATH=nextjs-fastapi && pytest nextjs-fastapi/tests/unit_tests

    # Run integration tests
    - name: Run integration tests
      run: |
        set PYTHONPATH=nextjs-fastapi && pytest nextjs-fastapi/tests/integration_tests

    # Start FastAPI backend
    - name: Start FastAPI backend
      working-directory: nextjs-fastapi/backend/controller
      run: |
        nohup uvicorn main:app --host 0.0.0.0 --port 8000 --reload &

    # Start Next.js frontend
    - name: Start Next.js frontend
      working-directory: nextjs-fastapi/frontend
      run: |
        nohup npm run dev &

    # Wait for services to start
    - name: Wait for services to start
      run: |
        sleep 5

    # Run Selenium tests
    - name: Run Selenium tests
      run: |
        set PYTHONPATH=nextjs-fastapi && pytest nextjs-fastapi/tests/feature_tests/

    # Clean up containers
    - name: Clean up containers
      run: |
        docker stop nextjs-backend nextjs-frontend selenium
        docker rm nextjs-backend nextjs-frontend selenium
        docker network rm my-network
