name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - SCRUM-101  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install --target=. -r nextjs-fastapi/backend/controller/requirements.txt

      - name: Archive deployment package
        run: |
        cd nextjs-fastapi/backend/
        zip -r fastapi_app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "vulcans-pantheon"
          publish-profile: '<publishData><publishProfile profileName="vulcans-pantheon - Web Deploy" publishMethod="MSDeploy" publishUrl="vulcans-pantheon-chfgbtenf5hphdbd.scm.canadacentral-01.azurewebsites.net:443" msdeploySite="vulcans-pantheon" userName="$vulcans-pantheon" userPWD="czhtcFycfw8HiSdw0DEesQb9DoPbMMGohckahy8nQEQecJ12oDeTvJPmRJ7g" destinationAppUrl="https://vulcans-pantheon-chfgbtenf5hphdbd.canadacentral-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="vulcans-pantheon - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-yt1-083.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="vulcans-pantheon\$vulcans-pantheon" userPWD="czhtcFycfw8HiSdw0DEesQb9DoPbMMGohckahy8nQEQecJ12oDeTvJPmRJ7g" destinationAppUrl="https://vulcans-pantheon-chfgbtenf5hphdbd.canadacentral-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="vulcans-pantheon - Zip Deploy" publishMethod="ZipDeploy" publishUrl="vulcans-pantheon-chfgbtenf5hphdbd.scm.canadacentral-01.azurewebsites.net:443" userName="$vulcans-pantheon" userPWD="czhtcFycfw8HiSdw0DEesQb9DoPbMMGohckahy8nQEQecJ12oDeTvJPmRJ7g" destinationAppUrl="https://vulcans-pantheon-chfgbtenf5hphdbd.canadacentral-01.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="https://portal.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
          package: nextjs-fastapi/backend/fastapi_app.zip

      
