name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - SCRUM-101  # Change this if using a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10 

      - name: Install dependencies
        run: |
            cd nextjs-fastapi/backend/controller
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
       

      - name: Archive deployment package
        run: cd nextjs-fastapi/backend/controller && zip -r fastapi_app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "pantheon3dp"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: nextjs-fastapi/backend/controller/fastapi_app.zip
          
